### PR TITLE
Replace external shell call with read-upto

### PR DESCRIPTION
**Pull request by zzamboni**
Elvish now has `read-upto`, which eliminates the need to call an external Bourne shell command to read the gitstatusd response.

### CODE REVIEW

**Comment by xiaq** [comment]
Note that `read-upto` was not in v0.13; it was added *before* v0.13 was released, but *after* the splitting of the release branch.

**Comment by zzamboni** [comment]
@xiaq thanks for the clarification. I have updated the title and description of the PR. Hopefully there will be a 0.13.1 soon which can include it :)

**Comment by Crestwave** [comment]
The commit itself still specifies 0.13, though

**Comment by zzamboni** [comment]
Fair enough. I'll close this one and resubmit with cleaned-up commits and branch name :)

**Pull request closed without merging**
